# Define the default configuration at the top
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Development environment settings
development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

# Test environment settings
test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

# Production environment settings
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>