default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sample_app_development
  username: <your_database_user>
  password: <your_database_password>
  host: localhost # Use 'localhost' or the appropriate host for your setup

test:
  <<: *default
  database: sample_app_test
  username: <your_database_user>
  password: <your_database_password>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # For Render